//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.15 at 03:07:29 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.openapplications.org/oagis/9/languagecode/5639:1988")
package org.openapplications.oagis._9.languagecode._5639._1988;
