//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.15 at 03:08:51 PM EST 
//


package org.hr_xml._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AuditTrailTypeCodeEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AuditTrailTypeCodeEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="I-9"/>
 *     &lt;enumeration value="EVerify"/>
 *     &lt;enumeration value="Comment"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AuditTrailTypeCodeEnumType", namespace = "http://www.hr-xml.org/3")
@XmlEnum
public enum AuditTrailTypeCodeEnumType {

    @XmlEnumValue("I-9")
    I_9("I-9"),
    @XmlEnumValue("EVerify")
    E_VERIFY("EVerify"),
    @XmlEnumValue("Comment")
    COMMENT("Comment");
    private final String value;

    AuditTrailTypeCodeEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AuditTrailTypeCodeEnumType fromValue(String v) {
        for (AuditTrailTypeCodeEnumType c: AuditTrailTypeCodeEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
