//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.15 at 03:08:51 PM EST 
//


package org.hr_xml._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChargeDispositionCodeEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ChargeDispositionCodeEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="Acquitted"/>
 *     &lt;enumeration value="AdjournedToADateToBeFixed"/>
 *     &lt;enumeration value="AdjudicatedGuilty"/>
 *     &lt;enumeration value="AdjudicationWithheld"/>
 *     &lt;enumeration value="ARDProgram"/>
 *     &lt;enumeration value="AcceleratedRehabilitativeDisposition"/>
 *     &lt;enumeration value="Acquitted"/>
 *     &lt;enumeration value="AdjournedTo"/>
 *     &lt;enumeration value="AdjournedToADateToBeFixed"/>
 *     &lt;enumeration value="AdjudgedDelinquent"/>
 *     &lt;enumeration value="AdjudicatedGuilty"/>
 *     &lt;enumeration value="AdjudicationWithheld"/>
 *     &lt;enumeration value="ARDProgram"/>
 *     &lt;enumeration value="BailBondForfeiture"/>
 *     &lt;enumeration value="ChargeDropped"/>
 *     &lt;enumeration value="ConditionalDischarge"/>
 *     &lt;enumeration value="ConsentDecreeJuvenile"/>
 *     &lt;enumeration value="Convicted"/>
 *     &lt;enumeration value="ConvictionVacated"/>
 *     &lt;enumeration value="DeadDocket"/>
 *     &lt;enumeration value="DeferredAdjudication"/>
 *     &lt;enumeration value="DeferredJudgment"/>
 *     &lt;enumeration value="Dismissed"/>
 *     &lt;enumeration value="GuiltyByWaiver"/>
 *     &lt;enumeration value="Disposedbywaiver"/>
 *     &lt;enumeration value="Diversion"/>
 *     &lt;enumeration value="Dropped"/>
 *     &lt;enumeration value="Expunged"/>
 *     &lt;enumeration value="FoundGuilty"/>
 *     &lt;enumeration value="FoundNotGuilty"/>
 *     &lt;enumeration value="FugitiveFile"/>
 *     &lt;enumeration value="Guilty"/>
 *     &lt;enumeration value="GuiltyByJuryTrial"/>
 *     &lt;enumeration value="GuiltyInAbsentia"/>
 *     &lt;enumeration value="Ignored"/>
 *     &lt;enumeration value="Infraction"/>
 *     &lt;enumeration value="InstantVerdict"/>
 *     &lt;enumeration value="JudgmentStayed"/>
 *     &lt;enumeration value="JudgmentWithheld"/>
 *     &lt;enumeration value="LetterOfReleaseFiled"/>
 *     &lt;enumeration value="MisdemeanorInterventionProgram"/>
 *     &lt;enumeration value="NoAction"/>
 *     &lt;enumeration value="NoBilled"/>
 *     &lt;enumeration value="NoFindingOfGuilt"/>
 *     &lt;enumeration value="NoInformation"/>
 *     &lt;enumeration value="NoInformationFiled"/>
 *     &lt;enumeration value="NolleProsse"/>
 *     &lt;enumeration value="NoloContendre"/>
 *     &lt;enumeration value="NonAdjudicationOfGuilt"/>
 *     &lt;enumeration value="NonSuit"/>
 *     &lt;enumeration value="NoPapered"/>
 *     &lt;enumeration value="NotGuilty"/>
 *     &lt;enumeration value="OrderForArrest"/>
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="PassedToFile"/>
 *     &lt;enumeration value="PeaceBond"/>
 *     &lt;enumeration value="Pending"/>
 *     &lt;enumeration value="PledGuilty"/>
 *     &lt;enumeration value="PledNolloContendre"/>
 *     &lt;enumeration value="PledNoloContendre"/>
 *     &lt;enumeration value="PrayerForJudgement"/>
 *     &lt;enumeration value="PretrialIntervention"/>
 *     &lt;enumeration value="ProbationBeforeJudgement"/>
 *     &lt;enumeration value="ProbationWithoutVerdict"/>
 *     &lt;enumeration value="ProcessOther"/>
 *     &lt;enumeration value="Prohibition"/>
 *     &lt;enumeration value="ProsecutionPending"/>
 *     &lt;enumeration value="Refused"/>
 *     &lt;enumeration value="Rejected"/>
 *     &lt;enumeration value="Remanded"/>
 *     &lt;enumeration value="RemandedToFile"/>
 *     &lt;enumeration value="RemandedToFileNextCourtDate"/>
 *     &lt;enumeration value="Responsible"/>
 *     &lt;enumeration value="Retired"/>
 *     &lt;enumeration value="RetiredToFile"/>
 *     &lt;enumeration value="SetDocket"/>
 *     &lt;enumeration value="Stet"/>
 *     &lt;enumeration value="StrickenOffLeave"/>
 *     &lt;enumeration value="TransferredToCaseNumber"/>
 *     &lt;enumeration value="TransferredToGrandJury"/>
 *     &lt;enumeration value="WaivedPledGuilty"/>
 *     &lt;enumeration value="Waiver"/>
 *     &lt;enumeration value="WaiverGuilty"/>
 *     &lt;enumeration value="Warrant Issued"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ChargeDispositionCodeEnumType", namespace = "http://www.hr-xml.org/3")
@XmlEnum
public enum ChargeDispositionCodeEnumType {

    @XmlEnumValue("Acquitted")
    ACQUITTED("Acquitted"),

    /**
     * Deprecated 2011-04-27.  Use CourtAction.
     * 
     */
    @XmlEnumValue("AdjournedToADateToBeFixed")
    ADJOURNED_TO_A_DATE_TO_BE_FIXED("AdjournedToADateToBeFixed"),
    @XmlEnumValue("AdjudicatedGuilty")
    ADJUDICATED_GUILTY("AdjudicatedGuilty"),
    @XmlEnumValue("AdjudicationWithheld")
    ADJUDICATION_WITHHELD("AdjudicationWithheld"),

    /**
     * An accelerated rehabilitative disposition (ARD) program is a special pre-trial intervention program for non-violent offenders who have limited or no prior record. Defendants in the Program are fast-tracked into rehabilitative programs, such as alcohol education. Offenders may also be ordered to complete varying amounts of Community Service as a condition of the Program.			
     * 
     * 
     */
    @XmlEnumValue("ARDProgram")
    ARD_PROGRAM("ARDProgram"),

    /**
     * An accelerated rehabilitative disposition (ARD) program is a special pre-trial intervention program for non-violent offenders who have limited or no prior record. Defendants in the Program are fast-tracked into rehabilitative programs, such as alcohol education. Offenders may also be ordered to complete varying amounts of Community Service as a condition of the Program.			
     * 
     * 
     */
    @XmlEnumValue("AcceleratedRehabilitativeDisposition")
    ACCELERATED_REHABILITATIVE_DISPOSITION("AcceleratedRehabilitativeDisposition"),

    /**
     * Deprecated 2011-04-27.  Use CourtAction.
     * 
     */
    @XmlEnumValue("AdjournedTo")
    ADJOURNED_TO("AdjournedTo"),
    @XmlEnumValue("AdjudgedDelinquent")
    ADJUDGED_DELINQUENT("AdjudgedDelinquent"),

    /**
     * Deprecated 2011-04-27.  Use CourtAction.
     * 
     */
    @XmlEnumValue("BailBondForfeiture")
    BAIL_BOND_FORFEITURE("BailBondForfeiture"),
    @XmlEnumValue("ChargeDropped")
    CHARGE_DROPPED("ChargeDropped"),

    /**
     * Deprecated 2011-04-27.  This is a sentence. The disposition could be guilty, diversion, etc.
     * 
     */
    @XmlEnumValue("ConditionalDischarge")
    CONDITIONAL_DISCHARGE("ConditionalDischarge"),

    /**
     * Deprecated 2011-04-27. Use CourtAction.  Used by juvenile courts.  Can drop charges when consent decree.
     * 
     */
    @XmlEnumValue("ConsentDecreeJuvenile")
    CONSENT_DECREE_JUVENILE("ConsentDecreeJuvenile"),
    @XmlEnumValue("Convicted")
    CONVICTED("Convicted"),

    /**
     * Deprecated 2011-04-27.  Use CourtAction.
     * 
     */
    @XmlEnumValue("ConvictionVacated")
    CONVICTION_VACATED("ConvictionVacated"),
    @XmlEnumValue("DeadDocket")
    DEAD_DOCKET("DeadDocket"),
    @XmlEnumValue("DeferredAdjudication")
    DEFERRED_ADJUDICATION("DeferredAdjudication"),
    @XmlEnumValue("DeferredJudgment")
    DEFERRED_JUDGMENT("DeferredJudgment"),
    @XmlEnumValue("Dismissed")
    DISMISSED("Dismissed"),
    @XmlEnumValue("GuiltyByWaiver")
    GUILTY_BY_WAIVER("GuiltyByWaiver"),

    /**
     * Deprecated 2011-04-27.  Use GuiltyByWaiver.	
     * 
     */
    @XmlEnumValue("Disposedbywaiver")
    DISPOSEDBYWAIVER("Disposedbywaiver"),
    @XmlEnumValue("Diversion")
    DIVERSION("Diversion"),
    @XmlEnumValue("Dropped")
    DROPPED("Dropped"),

    /**
     * Deprecated 2011-04-27.  Use CourtAction.
     * 
     */
    @XmlEnumValue("Expunged")
    EXPUNGED("Expunged"),
    @XmlEnumValue("FoundGuilty")
    FOUND_GUILTY("FoundGuilty"),
    @XmlEnumValue("FoundNotGuilty")
    FOUND_NOT_GUILTY("FoundNotGuilty"),

    /**
     * Deprecated 2011-04-27.  Use CourtAction.  Disposition would contain a value such as Guilty, Convicted, etc.		
     * 
     * 
     */
    @XmlEnumValue("FugitiveFile")
    FUGITIVE_FILE("FugitiveFile"),
    @XmlEnumValue("Guilty")
    GUILTY("Guilty"),
    @XmlEnumValue("GuiltyByJuryTrial")
    GUILTY_BY_JURY_TRIAL("GuiltyByJuryTrial"),
    @XmlEnumValue("GuiltyInAbsentia")
    GUILTY_IN_ABSENTIA("GuiltyInAbsentia"),
    @XmlEnumValue("Ignored")
    IGNORED("Ignored"),

    /**
     * Deprecated 2011-04-27.  Use ChargeLevel.
     * 
     */
    @XmlEnumValue("Infraction")
    INFRACTION("Infraction"),
    @XmlEnumValue("InstantVerdict")
    INSTANT_VERDICT("InstantVerdict"),
    @XmlEnumValue("JudgmentStayed")
    JUDGMENT_STAYED("JudgmentStayed"),
    @XmlEnumValue("JudgmentWithheld")
    JUDGMENT_WITHHELD("JudgmentWithheld"),
    @XmlEnumValue("LetterOfReleaseFiled")
    LETTER_OF_RELEASE_FILED("LetterOfReleaseFiled"),
    @XmlEnumValue("MisdemeanorInterventionProgram")
    MISDEMEANOR_INTERVENTION_PROGRAM("MisdemeanorInterventionProgram"),
    @XmlEnumValue("NoAction")
    NO_ACTION("NoAction"),
    @XmlEnumValue("NoBilled")
    NO_BILLED("NoBilled"),
    @XmlEnumValue("NoFindingOfGuilt")
    NO_FINDING_OF_GUILT("NoFindingOfGuilt"),
    @XmlEnumValue("NoInformation")
    NO_INFORMATION("NoInformation"),
    @XmlEnumValue("NoInformationFiled")
    NO_INFORMATION_FILED("NoInformationFiled"),
    @XmlEnumValue("NolleProsse")
    NOLLE_PROSSE("NolleProsse"),

    /**
     * Deprecated 2011-04-27.  Use CourtAction.
     * 
     */
    @XmlEnumValue("NoloContendre")
    NOLO_CONTENDRE("NoloContendre"),
    @XmlEnumValue("NonAdjudicationOfGuilt")
    NON_ADJUDICATION_OF_GUILT("NonAdjudicationOfGuilt"),
    @XmlEnumValue("NonSuit")
    NON_SUIT("NonSuit"),
    @XmlEnumValue("NoPapered")
    NO_PAPERED("NoPapered"),
    @XmlEnumValue("NotGuilty")
    NOT_GUILTY("NotGuilty"),

    /**
     * Deprecated 2011-04-27.  Use CourtAction.
     * 
     */
    @XmlEnumValue("OrderForArrest")
    ORDER_FOR_ARREST("OrderForArrest"),

    /**
     * Deprecated 2011-04-27.  This is an open list so not required.
     * 
     */
    @XmlEnumValue("Other")
    OTHER("Other"),
    @XmlEnumValue("PassedToFile")
    PASSED_TO_FILE("PassedToFile"),
    @XmlEnumValue("PeaceBond")
    PEACE_BOND("PeaceBond"),
    @XmlEnumValue("Pending")
    PENDING("Pending"),
    @XmlEnumValue("PledGuilty")
    PLED_GUILTY("PledGuilty"),

    /**
     * Deprecated 2011-04-27.  Use 	PledNoloContendre.	
     * 
     */
    @XmlEnumValue("PledNolloContendre")
    PLED_NOLLO_CONTENDRE("PledNolloContendre"),
    @XmlEnumValue("PledNoloContendre")
    PLED_NOLO_CONTENDRE("PledNoloContendre"),
    @XmlEnumValue("PrayerForJudgement")
    PRAYER_FOR_JUDGEMENT("PrayerForJudgement"),
    @XmlEnumValue("PretrialIntervention")
    PRETRIAL_INTERVENTION("PretrialIntervention"),
    @XmlEnumValue("ProbationBeforeJudgement")
    PROBATION_BEFORE_JUDGEMENT("ProbationBeforeJudgement"),
    @XmlEnumValue("ProbationWithoutVerdict")
    PROBATION_WITHOUT_VERDICT("ProbationWithoutVerdict"),

    /**
     * Deprecated 2011-04-27.  Not a disposition by itself - it needs additional description.
     * 
     */
    @XmlEnumValue("ProcessOther")
    PROCESS_OTHER("ProcessOther"),
    @XmlEnumValue("Prohibition")
    PROHIBITION("Prohibition"),
    @XmlEnumValue("ProsecutionPending")
    PROSECUTION_PENDING("ProsecutionPending"),
    @XmlEnumValue("Refused")
    REFUSED("Refused"),
    @XmlEnumValue("Rejected")
    REJECTED("Rejected"),
    @XmlEnumValue("Remanded")
    REMANDED("Remanded"),
    @XmlEnumValue("RemandedToFile")
    REMANDED_TO_FILE("RemandedToFile"),
    @XmlEnumValue("RemandedToFileNextCourtDate")
    REMANDED_TO_FILE_NEXT_COURT_DATE("RemandedToFileNextCourtDate"),
    @XmlEnumValue("Responsible")
    RESPONSIBLE("Responsible"),
    @XmlEnumValue("Retired")
    RETIRED("Retired"),
    @XmlEnumValue("RetiredToFile")
    RETIRED_TO_FILE("RetiredToFile"),

    /**
     * Deprecated 2011-04-27.  Use Stet.	
     * 
     */
    @XmlEnumValue("SetDocket")
    SET_DOCKET("SetDocket"),
    @XmlEnumValue("Stet")
    STET("Stet"),
    @XmlEnumValue("StrickenOffLeave")
    STRICKEN_OFF_LEAVE("StrickenOffLeave"),
    @XmlEnumValue("TransferredToCaseNumber")
    TRANSFERRED_TO_CASE_NUMBER("TransferredToCaseNumber"),
    @XmlEnumValue("TransferredToGrandJury")
    TRANSFERRED_TO_GRAND_JURY("TransferredToGrandJury"),

    /**
     * Deprecated 2011-04-27.  Use WaiverGuilty.
     * 
     */
    @XmlEnumValue("WaivedPledGuilty")
    WAIVED_PLED_GUILTY("WaivedPledGuilty"),

    /**
     * Deprecated 2011-04-27.  Use WaiverGuilty.
     * 
     */
    @XmlEnumValue("Waiver")
    WAIVER("Waiver"),
    @XmlEnumValue("WaiverGuilty")
    WAIVER_GUILTY("WaiverGuilty"),
    @XmlEnumValue("Warrant Issued")
    WARRANT_ISSUED("Warrant Issued");
    private final String value;

    ChargeDispositionCodeEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ChargeDispositionCodeEnumType fromValue(String v) {
        for (ChargeDispositionCodeEnumType c: ChargeDispositionCodeEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
