//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.15 at 03:08:51 PM EST 
//


package org.hr_xml._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IDCardTypeCodeEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IDCardTypeCodeEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="DentalInsurance"/>
 *     &lt;enumeration value="HealthInsurance"/>
 *     &lt;enumeration value="PrescriptionDrugServiceInsurance"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "IDCardTypeCodeEnumType", namespace = "http://www.hr-xml.org/3")
@XmlEnum
public enum IDCardTypeCodeEnumType {

    @XmlEnumValue("DentalInsurance")
    DENTAL_INSURANCE("DentalInsurance"),
    @XmlEnumValue("HealthInsurance")
    HEALTH_INSURANCE("HealthInsurance"),
    @XmlEnumValue("PrescriptionDrugServiceInsurance")
    PRESCRIPTION_DRUG_SERVICE_INSURANCE("PrescriptionDrugServiceInsurance");
    private final String value;

    IDCardTypeCodeEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IDCardTypeCodeEnumType fromValue(String v) {
        for (IDCardTypeCodeEnumType c: IDCardTypeCodeEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
