//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.15 at 03:08:51 PM EST 
//


package org.hr_xml._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ScreeningVendorOrderEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ScreeningVendorOrderEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="PreScreened"/>
 *     &lt;enumeration value="PreIndexed"/>
 *     &lt;enumeration value="Standard"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ScreeningVendorOrderEnumType", namespace = "http://www.hr-xml.org/3")
@XmlEnum
public enum ScreeningVendorOrderEnumType {


    /**
     * 
     * 						
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:1.1" xmlns="http://www.hr-xml.org/3" xmlns:clm54217="http://www.openapplications.org/oagis/9/currencycode/54217:2001" xmlns:oac="http://www.openapplications.org/oagis/9" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Pre Screened. Code&lt;/ccts:DictionaryEntryName&gt;
     * </pre>
     * 
     * 						
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:DefinitionText xmlns:ccts="urn:un:unece:uncefact:documentation:1.1" xmlns="http://www.hr-xml.org/3" xmlns:clm54217="http://www.openapplications.org/oagis/9/currencycode/54217:2001" xmlns:oac="http://www.openapplications.org/oagis/9" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Any search on a subject that has been prescreened from a greater group of subjects with the intent being to eliminate from that original group most or all   subjects with Negative Results, so that only subjects with Positive Results need be submitted to the provider.  If a subject has been prescreened the customer is fully expected to disclose  the fact upfront.&lt;/ccts:DefinitionText&gt;
     * </pre>
     * 
     * 						
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:UsageRule xmlns:ccts="urn:un:unece:uncefact:documentation:1.1" xmlns="http://www.hr-xml.org/3" xmlns:clm54217="http://www.openapplications.org/oagis/9/currencycode/54217:2001" xmlns:oac="http://www.openapplications.org/oagis/9" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;HR-XML open list.&lt;/ccts:UsageRule&gt;
     * </pre>
     * 
     * 					
     * 
     */
    @XmlEnumValue("PreScreened")
    PRE_SCREENED("PreScreened"),

    /**
     * 
     * 						
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:1.1" xmlns="http://www.hr-xml.org/3" xmlns:clm54217="http://www.openapplications.org/oagis/9/currencycode/54217:2001" xmlns:oac="http://www.openapplications.org/oagis/9" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Pre Screened. Code&lt;/ccts:DictionaryEntryName&gt;
     * </pre>
     * 
     * 						
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:DefinitionText xmlns:ccts="urn:un:unece:uncefact:documentation:1.1" xmlns="http://www.hr-xml.org/3" xmlns:clm54217="http://www.openapplications.org/oagis/9/currencycode/54217:2001" xmlns:oac="http://www.openapplications.org/oagis/9" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;A search request on a subject who has been pre-indexed has been Pre-researched by the requestor, the requestor’s customer, et cetera, on either 
     * the same index (or some version thereof) that the provider is now being requested to search.  While the pre-indexed search does not necessarily equate to prescreening (e.g. see salted search), all prescreened searches have by definition been pre-indexed.&lt;/ccts:DefinitionText&gt;
     * </pre>
     * 
     * 						
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:UsageRule xmlns:ccts="urn:un:unece:uncefact:documentation:1.1" xmlns="http://www.hr-xml.org/3" xmlns:clm54217="http://www.openapplications.org/oagis/9/currencycode/54217:2001" xmlns:oac="http://www.openapplications.org/oagis/9" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;HR-XML open list.&lt;/ccts:UsageRule&gt;
     * </pre>
     * 
     * 					
     * 
     */
    @XmlEnumValue("PreIndexed")
    PRE_INDEXED("PreIndexed"),

    /**
     * 
     * 						
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:1.1" xmlns="http://www.hr-xml.org/3" xmlns:clm54217="http://www.openapplications.org/oagis/9/currencycode/54217:2001" xmlns:oac="http://www.openapplications.org/oagis/9" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Standard. Code&lt;/ccts:DictionaryEntryName&gt;
     * </pre>
     * 
     * 						
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:DefinitionText xmlns:ccts="urn:un:unece:uncefact:documentation:1.1" xmlns="http://www.hr-xml.org/3" xmlns:clm54217="http://www.openapplications.org/oagis/9/currencycode/54217:2001" xmlns:oac="http://www.openapplications.org/oagis/9" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;No pre-indexing or pre-screening has taken place.&lt;/ccts:DefinitionText&gt;
     * </pre>
     * 
     * 						
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:UsageRule xmlns:ccts="urn:un:unece:uncefact:documentation:1.1" xmlns="http://www.hr-xml.org/3" xmlns:clm54217="http://www.openapplications.org/oagis/9/currencycode/54217:2001" xmlns:oac="http://www.openapplications.org/oagis/9" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;HR-XML open list.&lt;/ccts:UsageRule&gt;
     * </pre>
     * 
     * 					
     * 
     */
    @XmlEnumValue("Standard")
    STANDARD("Standard");
    private final String value;

    ScreeningVendorOrderEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ScreeningVendorOrderEnumType fromValue(String v) {
        for (ScreeningVendorOrderEnumType c: ScreeningVendorOrderEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
