//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.15 at 03:08:51 PM EST 
//


package org.hr_xml._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ScreeningVendorResultCodeEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ScreeningVendorResultCodeEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="RecordFound"/>
 *     &lt;enumeration value="NoRecordFound"/>
 *     &lt;enumeration value="Clear"/>
 *     &lt;enumeration value="Hit"/>
 *     &lt;enumeration value="UnableToFulfill"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ScreeningVendorResultCodeEnumType", namespace = "http://www.hr-xml.org/3")
@XmlEnum
public enum ScreeningVendorResultCodeEnumType {


    /**
     * Indicates within the boundaries of any pre-existing understanding between  provider and CRA  that negative information resulted from the screening.
     * 
     */
    @XmlEnumValue("RecordFound")
    RECORD_FOUND("RecordFound"),

    /**
     * Indicates within the boundaries of any pre-existing understanding between  provider and CRA that no  results or records where located." 
     * 
     */
    @XmlEnumValue("NoRecordFound")
    NO_RECORD_FOUND("NoRecordFound"),

    /**
     * Indicates the screening did not return any  results or records." 
     * 
     */
    @XmlEnumValue("Clear")
    CLEAR("Clear"),

    /**
     * Indicates within the boundaries of any pre-existing understanding between  provider and CRA that no  results or records where located." 
     * 
     */
    @XmlEnumValue("Hit")
    HIT("Hit"),

    /**
     * Indicates that the screening could not be fulfilled.  For example, court has been closed for undetermined determination of time due to natual disaster.  Additional information would be provided in the appropriate comments section." 
     * 
     */
    @XmlEnumValue("UnableToFulfill")
    UNABLE_TO_FULFILL("UnableToFulfill");
    private final String value;

    ScreeningVendorResultCodeEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ScreeningVendorResultCodeEnumType fromValue(String v) {
        for (ScreeningVendorResultCodeEnumType c: ScreeningVendorResultCodeEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
